title: 7OOP
description: "JoshuaCoronelC204 - A collection of my coding projects, experiments, and a dash of existential dread."

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown

remote_theme: pages-themes/primer@v0.6.0
