title: 7OOP
description: "JoshuaCoronelC204 - A collection of my coding projects, experiments, and a dash of existential dread."

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme # This plugin is required for remote themes to work

markdown: kramdown

remote_theme: "yaoyao-liu/minimal-light"
