title: 7OOP
description: "JoshuaCoronelC204 - It contains all the activities and projects I’ve done! :)"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

markdown: kramdown

remote_theme: "jeffreytse/jekyll-theme-yat"
